disableHugoGeneratorInject: true
disableKinds:
  - taxonomy
  - taxonomyTerm
  - RSS
  - sitemap

languageCode: en-us
baseURL: https://edvinas.dev

markup:
  highlight:
    codeFences: false

  goldmark:
    renderer:
      xHTML: true

params:
  description: Programming, music and other relevant things
  author: Edvinas Danevičius
  name: edvinas.dev
  images:
    - icon.png
