disableHugoGeneratorInject: true
disableKinds:
  - taxonomy
  - taxonomyTerm
  - RSS
  - sitemap

languageCode: en-us
baseURL: https://edvinas.dev

markup:

  # TODO: use Goldmark once it has hrefTargetBlank feature.
  defaultMarkdownHandler: blackFriday

  blackFriday:
    hrefTargetBlank: true
    noreferrerLinks: true

params:
  description: Programming, music and other relevant things
  author: Edvinas
  name: edvinas.dev
  images:
    - icon.png
