disableHugoGeneratorInject: true
disableKinds:
  - taxonomy
  - taxonomyTerm
  - RSS
  - sitemap

languageCode: en-us
baseURL: https://edvinas.dev

pygmentsUseClasses: true
pygmentsStyle: github

blackfriday:
  hrefTargetBlank: true

params:
  description: Programming and other random stuff
  author: Edvinas
  images:
    - /icon.png
