disableHugoGeneratorInject: true
disableKinds:
  - taxonomy
  - taxonomyTerm
  - RSS
  - sitemap

languageCode: en-us
baseURL: https://edvinas.dev

pygmentsUseClasses: true
pygmentsStyle: github

markup:

  # TODO: use Goldmark once it has hrefTargetBlank feature.
  defaultMarkdownHandler: blackFriday

  blackFriday:
    hrefTargetBlank: true

params:
  description: Programming and other random stuff
  author: Edvinas
  images:
    - /icon.png
