version: 2

jobs:
  build:
    branches:
      ignore:
        - gh-pages

    environment:
      GH_SRC_BRANCH: master
      GH_DST_BRANCH: gh-pages

    docker:
      - image: cibuilds/hugo:0.55.6

    working_directory: ~/repo

    steps:
      - checkout
      - run: hugo --verbose --minify
      - run: ./deploy.sh
